[package]
name = "testudo-types"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
rust_decimal = { version = "1.34.3", features = ["serde-with-str"] }
serde = { version = "1.0.196", features = ["derive"] }
thiserror = "1.0.57"