# Testudo Trading Platform - Default Configuration
# Roman Military Discipline in Configuration Management

[server]
host = "0.0.0.0"
port = 3000
max_connections = 1000

[database]
url = "postgresql://testudo:disciplina@localhost:5432/testudo"
max_connections = 20
min_connections = 5
connection_timeout = "30s"
idle_timeout = "10m"

[redis]
url = "redis://localhost:6379"
pool_size = 20
connection_timeout = "5s"
command_timeout = "10s"

[security]
jwt_secret = "testudo-jwt-secret-change-in-production"
jwt_expiration_hours = 24
api_key_encryption_key = "disciplina-encryption-key-32-bytes"

[cors]
allowed_origins = ["http://localhost:3000", "http://localhost:5173"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]

[rate_limiting]
requests_per_minute = 60
burst_size = 10
window_size = "1m"

[websocket]
max_connections = 500
heartbeat_interval = 30
max_frame_size = 65536

# Van Tharp Position Sizing Configuration
[risk_management]
default_risk_percentage = 0.02  # 2% default risk per trade
max_risk_percentage = 0.06     # 6% maximum risk per trade  
min_risk_percentage = 0.005    # 0.5% minimum risk per trade
max_portfolio_risk = 0.10      # 10% maximum total portfolio risk
max_daily_loss = 0.05          # 5% maximum daily loss
max_consecutive_losses = 3      # Circuit breaker after 3 consecutive losses

# Exchange Configuration - Binance Primary
[exchanges.binance]
name = "binance"
base_url = "https://api.binance.com"
websocket_url = "wss://stream.binance.com:9443/ws"
api_key = ""  # Set via environment variable
api_secret = ""  # Set via environment variable
max_requests_per_minute = 1200
max_order_requests_per_second = 10
connect_timeout = "10s"
request_timeout = "30s"

# Circuit Breaker Configuration
[circuit_breaker]
failure_threshold = 5
recovery_timeout = "1m"
half_open_max_calls = 3

# OODA Loop Performance Targets
[ooda]
max_loop_duration = "200ms"
max_market_data_age = "5s"
max_observe_duration = "20ms"
max_orient_duration = "50ms" 
max_decide_duration = "30ms"
max_act_duration = "100ms"

# Monitoring and Observability
[monitoring]
metrics_enabled = true
tracing_enabled = true
error_reporting_enabled = true
performance_monitoring = true

[logging]
level = "info"
format = "json"
file_enabled = true
file_path = "logs/testudo.log"
max_file_size = "100MB"
max_files = 10

# Market Data Configuration
[market_data]
default_symbols = ["BTC/USDT", "ETH/USDT", "ADA/USDT", "SOL/USDT", "DOT/USDT"]
update_frequency = "100ms"
order_book_depth = 20
enable_trade_stream = true
enable_ticker_stream = true
data_retention_days = 90

# Database Migration Settings
[migrations]
auto_run = false  # Set to true for development, false for production
backup_before_migration = true

# Performance Optimization
[performance]
connection_pool_idle_timeout = "10m"
query_timeout = "30s"
bulk_insert_batch_size = 1000
cache_ttl = "5m"

# Security Hardening
[security.headers]
hsts_max_age = 31536000  # 1 year
content_security_policy = "default-src 'self'"
x_frame_options = "DENY"
x_content_type_options = "nosniff"

# Development vs Production Overrides
[development]
debug_mode = true
cors_permissive = true
auto_reload = true
detailed_errors = true

[production]
debug_mode = false
cors_permissive = false
auto_reload = false
detailed_errors = false
require_tls = true