// @anchor exchange:router:mod
// @tags api

pub mod agent_journal;
pub mod auth;
pub mod coach;
pub mod signal;
pub mod context;
pub mod dignitas;
pub mod internal;
pub mod public_profile;
pub mod depth;
pub mod exchanges;
pub mod imports;
pub mod journal;
pub mod klines;
pub mod market_data;
pub mod onboarding;
pub mod order;
pub mod paper_balance;
pub mod risk;
pub mod risk_config;
pub mod sync;
pub mod tickers;
pub mod trade;
pub mod trade_events;
pub mod trade_management;
pub mod user_settings;
